services:
  # Backend API Service
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGOOSE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: ecommerce-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ecommerce-backend.onrender.com
      - key: REACT_APP_RAZORPAY_KEY_ID
        sync: false
    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable 